server:
  port: ${app.port:40000}
  error:
    include-binding-errors: always
    include-message: always
spring:
  application:
    name: user
  config:
    import: configserver:http://configuration:8888
  cloud:
    stream:
      bindings:
        mailOperationOutputChannel:
          destination: mail-service.operation
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: trendburada-rabbit
                port: 5672
                username: quest
                password: quest
                virtual-host: /
